-- [nfnl] fnl/plugins/avante.fnl
local _local_1_ = require("config.utils")
local g = _local_1_["g"]
local opts = {provider = "internal", providers = {internal = {__inherited_from = "openai", endpoint = "http://127.0.1:8899/v1", model = "gpt-4o", timeout = 30000, temperature = 0, max_completion_tokens = 81920, reasoning_effort = "medium"}, copilot = {endpoint = "https://api.github.com", model = "gpt-4o-2024-05-13", proxy = nil, timeout = 30000, allow_insecure = false}}, behaviour = {auto_set_highlight_group = true, auto_set_keymaps = true, minimize_diff = true, enable_token_counting = true, auto_apply_diff_after_generation = false, auto_suggestions = false, support_paste_from_clipboard = false}, mappings = {diff = {ours = "co", theirs = "ct", all_theirs = "ca", both = "cb", cursor = "cc", next = "]x", prev = "[x"}, suggestion = {accept = "<M-l>", next = "<M-]>", prev = "<M-[>", dismiss = "<C-]>"}, jump = {next = "]]", prev = "[["}, submit = {normal = "<CR>", insert = "<C-s>"}, sidebar = {apply_all = "A", apply_cursor = "a", switch_windows = "<Tab>", reverse_switch_windows = "<S-Tab>"}}, hints = {enabled = true}, windows = {position = "right", wrap = true, width = 30, sidebar_header = {enabled = true, align = "center", rounded = true}}, highlights = {diff = {current = "DiffText", incoming = "DiffAdd"}}, selector = {provider = "telescope", provider_opts = {}}}
local function _2_()
  local avante = require("avante")
  return avante.setup(opts)
end
return {{"yetone/avante.nvim", event = "VeryLazy", build = "make BUILD_FROM_SOURCE=true", dependencies = {"nvim-lua/plenary.nvim", "MunifTanjim/nui.nvim", "nvim-telescope/telescope.nvim", "hrsh7th/nvim-cmp", "nvim-tree/nvim-web-devicons", "zbirenbaum/copilot.lua", {"HakonHarnes/img-clip.nvim", event = "VeryLazy", opts = {default = {drag_and_drop = {insert_mode = true}, use_absolute_path = true, embed_image_as_base64 = false, prompt_for_file_name = false}}}, {"MeanderingProgrammer/render-markdown.nvim", opts = {file_types = {"markdown", "Avante"}}, ft = {"markdown", "Avante"}}}, keys = {{"<leader>aa", "<cmd>AvanteAsk<cr>", desc = "avante: ask"}, {"<leader>ar", "<cmd>AvanteRefresh<cr>", desc = "avante: refresh"}, {"<leader>ae", "<cmd>AvanteEdit<cr>", desc = "avante: edit", mode = {"n", "v"}}, {"<leader>at", "<cmd>AvanteToggle<cr>", desc = "avante: toggle"}, {"<leader>af", "<cmd>AvanteFocus<cr>", desc = "avante: focus"}, {"<leader>ac", "<cmd>AvanteClear<cr>", desc = "avante: clear"}, {"<leader>as", "<cmd>AvanteStop<cr>", desc = "avante: stop"}, {"<leader>ah", "<cmd>AvanteHistory<cr>", desc = "avante: history"}}, config = _2_, version = false}}
